// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// TimeZoneTransition is the golang structure for table time_zone_transition.
type TimeZoneTransition struct {
	TimeZoneId       uint  `json:"timeZoneId"       ` //
	TransitionTime   int64 `json:"transitionTime"   ` //
	TransitionTypeId uint  `json:"transitionTypeId" ` //
}
