// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Host                 string      `json:"host"                 ` //
	User                 string      `json:"user"                 ` //
	SelectPriv           string      `json:"selectPriv"           ` //
	InsertPriv           string      `json:"insertPriv"           ` //
	UpdatePriv           string      `json:"updatePriv"           ` //
	DeletePriv           string      `json:"deletePriv"           ` //
	CreatePriv           string      `json:"createPriv"           ` //
	DropPriv             string      `json:"dropPriv"             ` //
	ReloadPriv           string      `json:"reloadPriv"           ` //
	ShutdownPriv         string      `json:"shutdownPriv"         ` //
	ProcessPriv          string      `json:"processPriv"          ` //
	FilePriv             string      `json:"filePriv"             ` //
	GrantPriv            string      `json:"grantPriv"            ` //
	ReferencesPriv       string      `json:"referencesPriv"       ` //
	IndexPriv            string      `json:"indexPriv"            ` //
	AlterPriv            string      `json:"alterPriv"            ` //
	ShowDbPriv           string      `json:"showDbPriv"           ` //
	SuperPriv            string      `json:"superPriv"            ` //
	CreateTmpTablePriv   string      `json:"createTmpTablePriv"   ` //
	LockTablesPriv       string      `json:"lockTablesPriv"       ` //
	ExecutePriv          string      `json:"executePriv"          ` //
	ReplSlavePriv        string      `json:"replSlavePriv"        ` //
	ReplClientPriv       string      `json:"replClientPriv"       ` //
	CreateViewPriv       string      `json:"createViewPriv"       ` //
	ShowViewPriv         string      `json:"showViewPriv"         ` //
	CreateRoutinePriv    string      `json:"createRoutinePriv"    ` //
	AlterRoutinePriv     string      `json:"alterRoutinePriv"     ` //
	CreateUserPriv       string      `json:"createUserPriv"       ` //
	EventPriv            string      `json:"eventPriv"            ` //
	TriggerPriv          string      `json:"triggerPriv"          ` //
	CreateTablespacePriv string      `json:"createTablespacePriv" ` //
	SslType              string      `json:"sslType"              ` //
	SslCipher            []byte      `json:"sslCipher"            ` //
	X509Issuer           []byte      `json:"x509Issuer"           ` //
	X509Subject          []byte      `json:"x509Subject"          ` //
	MaxQuestions         uint        `json:"maxQuestions"         ` //
	MaxUpdates           uint        `json:"maxUpdates"           ` //
	MaxConnections       uint        `json:"maxConnections"       ` //
	MaxUserConnections   uint        `json:"maxUserConnections"   ` //
	Plugin               string      `json:"plugin"               ` //
	AuthenticationString string      `json:"authenticationString" ` //
	PasswordExpired      string      `json:"passwordExpired"      ` //
	PasswordLastChanged  *gtime.Time `json:"passwordLastChanged"  ` //
	PasswordLifetime     uint        `json:"passwordLifetime"     ` //
	AccountLocked        string      `json:"accountLocked"        ` //
}
