// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserForDao is the golang structure of table user for DAO operations like Where/Data.
type UserForDao struct {
	g.Meta               `orm:"dto:true"`
	Host                 interface{} //
	User                 interface{} //
	SelectPriv           interface{} //
	InsertPriv           interface{} //
	UpdatePriv           interface{} //
	DeletePriv           interface{} //
	CreatePriv           interface{} //
	DropPriv             interface{} //
	ReloadPriv           interface{} //
	ShutdownPriv         interface{} //
	ProcessPriv          interface{} //
	FilePriv             interface{} //
	GrantPriv            interface{} //
	ReferencesPriv       interface{} //
	IndexPriv            interface{} //
	AlterPriv            interface{} //
	ShowDbPriv           interface{} //
	SuperPriv            interface{} //
	CreateTmpTablePriv   interface{} //
	LockTablesPriv       interface{} //
	ExecutePriv          interface{} //
	ReplSlavePriv        interface{} //
	ReplClientPriv       interface{} //
	CreateViewPriv       interface{} //
	ShowViewPriv         interface{} //
	CreateRoutinePriv    interface{} //
	AlterRoutinePriv     interface{} //
	CreateUserPriv       interface{} //
	EventPriv            interface{} //
	TriggerPriv          interface{} //
	CreateTablespacePriv interface{} //
	SslType              interface{} //
	SslCipher            []byte      //
	X509Issuer           []byte      //
	X509Subject          []byte      //
	MaxQuestions         interface{} //
	MaxUpdates           interface{} //
	MaxConnections       interface{} //
	MaxUserConnections   interface{} //
	Plugin               interface{} //
	AuthenticationString interface{} //
	PasswordExpired      interface{} //
	PasswordLastChanged  *gtime.Time //
	PasswordLifetime     interface{} //
	AccountLocked        interface{} //
}
