// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	internal2 "github.com/gogf/gf/v2/net/gmetrics/example/metrics/dao/internal"
)

// timeZoneTransitionDao is the data access object for table time_zone_transition.
// You can define custom methods on it to extend its functionality as you wish.
type timeZoneTransitionDao struct {
	*internal2.TimeZoneTransitionDao
}

var (
	// TimeZoneTransition is globally public accessible object for table time_zone_transition operations.
	TimeZoneTransition = timeZoneTransitionDao{
		internal2.NewTimeZoneTransitionDao(),
	}
)

// Fill with you ideas below.
