// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	internal2 "github.com/gogf/gf/v2/net/gmetrics/example/metrics/dao/internal"
)

// userDao is the data access object for table user.
// You can define custom methods on it to extend its functionality as you wish.
type userDao struct {
	*internal2.UserDao
}

var (
	// User is globally public accessible object for table user operations.
	User = userDao{
		internal2.NewUserDao(),
	}
)

// Fill with you ideas below.
