// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TimeZoneTransitionDao is the data access object for table time_zone_transition.
type TimeZoneTransitionDao struct {
	Table   string                    // Table is the underlying table name of the DAO.
	Group   string                    // Group is the database configuration group name of current DAO.
	Columns TimeZoneTransitionColumns // Columns contains all the column names of Table for convenient usage.
}

// TimeZoneTransitionColumns defines and stores column names for table time_zone_transition.
type TimeZoneTransitionColumns struct {
	TimeZoneId       string //
	TransitionTime   string //
	TransitionTypeId string //
}

//  timeZoneTransitionColumns holds the columns for table time_zone_transition.
var timeZoneTransitionColumns = TimeZoneTransitionColumns{
	TimeZoneId:       "Time_zone_id",
	TransitionTime:   "Transition_time",
	TransitionTypeId: "Transition_type_id",
}

// NewTimeZoneTransitionDao creates and returns a new DAO object for table data access.
func NewTimeZoneTransitionDao() *TimeZoneTransitionDao {
	return &TimeZoneTransitionDao{
		Group:   "default",
		Table:   "time_zone_transition",
		Columns: timeZoneTransitionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TimeZoneTransitionDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TimeZoneTransitionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TimeZoneTransitionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
